rules:
  master:
    level: notice
  slave:
    level: notice
  whitelist:
    level: notice
  blacklist:
    level: notice
  segregation:
    regex: 
      - /segregation/gi
    level: notice
    alternatives: 
      - separation
ignore:
 - ".github/in-solidarity.yml"
